### PR TITLE
Silence the NS_ERROR_FAILURE message

### PR DESCRIPTION
**Pull request by vpzomtrrfrt**
Quite annoying to see this whenever I try to play

### CODE REVIEW

**Comment by grompe** [comment]
Why does it happen?

**Comment by vpzomtrrfrt** [comment]
Not sure, google search doesn't turn up much.  It looks like it might have something to do with the chat

**Comment by grompe** [comment]
Are you using buggy vesion of a browser?
Also, your code has syntax errors, I cannot accept it,

**Comment by vpzomtrrfrt** [comment]
Oops, fixed.  I assume my browser version isn't the issue, I'm on Firefox 44.0.1

**Comment by vpzomtrrfrt** [comment]
Somehow the PR isn't updated...?

**Pull request closed without merging**
